name: ci-release
on:
  push:
    tags:
      'v*'
  workflow_dispatch:
jobs:
  x64-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: |
            uname -m
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10
      - name: configure
        run: cmake -S . --preset=ninja-gcc -B build -DDEPZIP_INSTALL=ON -DDEPZIP_BUILD_TESTS=OFF
      - name: build release
        run: cmake --build build --config=Release -- -v
      - name: install
        run: |
            cmake --install build --config=Release --prefix=.
            tar -acf x64-linux-depzip-${{ github.ref_name }}.tar.xz bin/depzip
      - name: release
        uses: softprops/action-gh-release@v2.3.4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: x64-linux-depzip-${{ github.ref_name }}.tar.xz
          draft: true
          fail_on_unmatched_files: true
  arm64-linux-gcc:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: |
            uname -m
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 10
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10
      - name: configure
        run: cmake -S . --preset=ninja-gcc -B build -DDEPZIP_INSTALL=ON -DDEPZIP_BUILD_TESTS=OFF
      - name: build release
        run: cmake --build build --config=Release -- -v
      - name: install
        run: |
            cmake --install build --config=Release --prefix=.
            tar -acf arm64-linux-depzip-${{ github.ref_name }}.tar.xz bin/depzip
      - name: release
        uses: softprops/action-gh-release@v2.3.4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: arm64-linux-depzip-${{ github.ref_name }}.tar.xz
          draft: true
          fail_on_unmatched_files: true
  x64-windows-clang:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: cmake -S . --preset=ninja-clang -B build -DDEPZIP_INSTALL=ON -DDEPZIP_BUILD_TESTS=OFF
      - name: build release
        run: cmake --build build --config=Release -- -v
      - name: install
        run: |
            cmake --install build --config=Release --prefix=.
            tar -acf x64-windows-depzip-${{ github.ref_name }}.zip bin/depzip.exe
      - name: release
        uses: softprops/action-gh-release@v2.3.4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: x64-windows-depzip-${{ github.ref_name }}.zip
          draft: true
          fail_on_unmatched_files: true
